version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pub"
    directory: "/packages/stream_chat"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pub"
    directory: "/packages/stream_chat_flutter_core"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pub"
    directory: "/packages/stream_chat_flutter"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pub"
    directory: "/packages/stream_chat_persistence"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pub"
    directory: "/packages/stream_chat_localizations"
    schedule:
      interval: "weekly"
