name: stream_chat
homepage: https://getstream.io/
description: The official Dart client for Stream Chat, a service for building chat applications.
version: 6.6.0
repository: https://github.com/GetStream/stream-chat-flutter
issue_tracker: https://github.com/GetStream/stream-chat-flutter/issues

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  async: ^2.10.0
  collection: ^1.17.0
  dio: ^5.2.1+1
  equatable: ^2.0.5
  freezed_annotation: ^2.2.0
  http_parser: ^4.0.2
  jose: ^0.3.3
  json_annotation: ^4.8.1
  logging: ^1.2.0
  meta: ^1.8.0
  mime: ^1.0.4
  rate_limiter: ^1.0.0
  rxdart: ^0.27.7
  synchronized: ^3.1.0
  uuid: ^3.0.7
  web_socket_channel: ^2.4.0

dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^2.4.0
  json_serializable: ^6.6.2
  mocktail: ^0.3.0
  test: ^1.24.3
