name: stream_chat_flutter_core
homepage: https://github.com/GetStream/stream-chat-flutter
description: Stream Chat official Flutter SDK Core. Build your own chat experience using Dart and Flutter.
version: 6.7.0
repository: https://github.com/GetStream/stream-chat-flutter
issue_tracker: https://github.com/GetStream/stream-chat-flutter/issues

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  collection: ^1.17.0
  connectivity_plus: ^4.0.1
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0
  meta: ^1.8.0
  rxdart: ^0.27.7
  stream_chat: ^6.7.0

dev_dependencies:
  build_runner: ^2.3.3
  fake_async: ^1.3.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.0
  mocktail: ">=0.3.0 <2.0.0"

